title:            Platform Engineering Blog
description:      blog of a few engineers lost in space between dev and ops.
disqus_shortname: springerpe
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url:              http://springerpe.github.io
# production_url:              http://springerpe.github.io      
# author information
author_ids: [otte, keymon, simon, katter, jose, marc, josef, jorja, ryan, felix]
authors:
  otte:
    name: Daniel Otte
    job_title: Jefe Problemas
    display_name: Daniel Otte
    alias: el caPEtan
    gravatar: 1b2ba3880f13a8275537f5d6f70f8b84
    email: daniel.otte@springer.com
    twitter: Jef0tte
    github: daniel-otte
    bio: 'Just a regular dude, enabling people to do awesome things...'
  keymon:
    name: Hector Rivas
    display_name: Hector Rivas
    alias: Keymon
    gravatar: 7148b1821188bbdd1edcb6a561fedfc8
    twitter: thekeymon
    email: hector.rivas@springer.com
    github: keymon
    bio: I do yak shaving on linux boxes
  simon:
    name: Simon Johansson
    display_name: Simon Johansson
    alias: NoTouch!
    gravatar: c35be6b4c2eaab56aeafebbda3f6ecbd
    twitter: KarlSimonJohan
    github: simonjohansson
    email: simon@simonjohansson.com
    bio: I like music and computers.
  katter:
    name: Carsten Hiort
    job_title: Platform Engineer
    display_name: Carsten Hiort
    alias: Katter
    gravatar: 96e3edb3f903142c651c48b54146bf3c
    email: carsten.hiort@springer.com
    twitter: katterstrophe
    github: katter
    bio: 'Passionate father of two | Do it the Arch Way'
  jose:
    name: Jose Riguera
    job_title: Platform Engineer
    display_name: Jose Riguera
    alias: J.R.
    gravatar: dd74844ebd31abb30293a34eac18be8a
    email: jose.riguera@springer.com
    twitter: jose_riguera
    github: jriguera
    bio: 'Openstack guru'
  marc:
    name: Marc Driessen 
    job_title: Platform Engineer
    display_name: Marc Driessen 
    alias: 
    gravatar: e2191d2ba882b055cd64604249807da9 
    email: marc.driessena@springer.com
    twitter: marcdriessen 
    github: sprmarc 
    bio: 'I am dutch'
  josef:
    name: Josef Hoerandtner
    job_title: Platform Engineer
    display_name: Josef Hoerandtner
    alias: 
    gravatar: 4177dfb6a675547dcce2370f43b3a64f
    email: josef.hoerandtner@springer.com
    twitter: jhoerandtner
    github: jossy
    bio: 'unity user | continuous integrator | coffee culture advocate'
  ryan:
    name: Ryan Conway
    job_title: Platform Engineer
    display_name: Ryan Conway
    alias: Dashboard shipping ship
    gravatar: 
    email: ryan.conway@springer.com
    twitter: rylon 
    github:  
    bio: 'Builds stuff, breaks things and loves Rap Opera'
  felix:
    name: Felix Friedrich
    job_title: Platform Engineer
    display_name: Felix Friedrich
    alias: Face
    gravatar: 
    email: felix.friedrich@springer.com
    twitter: felixfriedrich 
    github:  
    bio:
  jorja:
    name: Jorja Hung
    job_title: Junior Web Developer
    display_name: Jorja Hung
    alias: the Fallen
    gravatar: e8f64120f5be55084c37184f6dbd292b
    email: jorja.hung@springer.com
    twitter: jorjski 
    github: jorjahung 
    bio: 'Ex Springer Pony'
# Owner
owner:
  name:           Platform Engineering
  avatar:         avatar.png
  bio:            "We are a global team of passionate engineers, who enable development teams rapidly produce, maintain and release software products and services."
  email:          Platform-Engineering@springer.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        springerpe
  facebook:       
  github:         springerpe
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    
# Analytics and webmaster tools stuff goes here
google_analytics: UA-51131138-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Springer Devs Blog
    url: http://spiking-the-solution.tumblr.com
    external: true
  - title: JoinIT
    url: http://joinit.springer.com
    external: true
  - title: Trello
    url: http://www.trello.com
    external: true
  - title: HipChat
    url: http://www.hipchat.com
    external: true


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 4
