title:            Platform Engineering Blog
description:      blog of a few engineers lost in space between dev and ops.
disqus_shortname: springerpe
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url:              http://springerpe.github.io
# production_url:              http://springerpe.github.io      
# author information
authors:
  otte:
    name: Daniel Otte
    display_name: Daniel Otte
    gravatar: 
    twitter: Jef0tte
  keymon:
    name: Hector Rivas
    display_name: Keymon
    gravatar: 642eef33b266eec5223c8010496b400f
    twitter: thekeymon
    email: hector.rivas@springer.com
    github: keymon
    bio: I do yak shaving on linux boxes
  simon:
    name: Simon Johansson
    display_name: Simon Johansson
    gravatar:
    twitter: KarlSimonJohan
    github: simonjohansson
    email: simon@simonjohansson.com
    bio: I like music and computers.
# Owner
owner:
  name:           Platform Engineering
  avatar:         avatar.jpg
  bio:            "We are a global team of passionate engineers, who enable development teams rapidly produce, maintain and release software products and services."
  email:          Platform-Engineerin@springer.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        springerpe
  facebook:       
  github:         springerpe
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    
# Analytics and webmaster tools stuff goes here
google_analytics: UA-51131138-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Springer Devs Blog
    url: http://spiking-the-solution.tumblr.com
    external: true
  - title: JoinIT
    url: http://joinit.springer.com
    external: true
  - title: Trello
    url: http://www.trello.com
    external: true
  - title: HipChat
    url: http://www.hipchat.com
    external: true


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5
